"""empty message

Revision ID: ec86ed04d47a
Revises: 453817d5f486
Create Date: 2023-02-27 15:45:35.787026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec86ed04d47a'
down_revision = '453817d5f486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

        # Now adding these manually so as to make proper upgrades in db
        op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
        op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
